decoherence:
  per_timeslot: 0.9
  per_measurement: 0.99
  qubit_ttl_threshold: 0.23
  epr_ttl_threshold: 0.1
fidelity:
  epr_threshold: 0.8
  purification_threshold: 0.8
  purification_min_probability: 0.5
  initial_epr_fidelity: 1.0
probability:
  epr_create_max: 1.0
  epr_create_min: 0.2
protocol:
  link_max_attempts: 2
  link_purification_after_failures: 2
  transport_max_attempts: 2
  entanglement_max_attempts: 5
defaults:
  qubits_per_host: 10
  eprs_per_channel: 10
  qubit_regen_interval: 0
  qubit_regen_amount: 3
  channel_noise_type: random
costs:
  heralding: 5
  on_demand: 1
  replay: 1
  purification: 1
  swapping: 1
  qubit_creation: 1
  e91_round: 1
  nepr_measurement: 1
topology:
  name: Line
  args:
  - '5'
