FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements-notebook.txt ./
RUN pip install --no-cache-dir -r requirements-notebook.txt

COPY . .

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--ServerApp.token="]
